// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Client struct {
	PkClientID string
	Name       string
}

type Metadata struct {
	FkRecordID    string
	CreatedAt     time.Time
	UpdatedAt     sql.NullTime
	FkCreatedByID string
	FkUpdatedByID sql.NullString
}

type Property struct {
	PkPropertyID       string
	Name               string
	Address            string
	IsDemo             bool
	FkPointOfContactID sql.NullString
	FkManagerID        sql.NullString
	FkClientID         string
}

type User struct {
	PkUserID  string
	FirstName string
	LastName  string
}
